openapi: 3.2.0
info:
  title: Acall Public Spot Reservation API
  version: v1
servers:
- url: https://api.workstyleos.com/v1/
security:
- Bearer: []
tags:
- name: Spot Reservation API
  x-displayName: スポット予約 API
paths:
  /spot_reservations/:
    get:
      operationId: getSpotReservations
      parameters:
      - description: 取得件数を指定します
        explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      - description: オフセットを指定します
        explode: true
        in: query
        name: offset
        required: false
        schema:
          type: integer
        style: form
      - description: spot_idより下の階層のスポット一覧を検索します
        explode: true
        in: query
        name: root_spot_id
        required: false
        schema:
          type: string
        style: form
      - description: 検索期間の開始日時を指定します
        explode: true
        in: query
        name: starting_at
        required: false
        schema:
          format: date-time
          type: string
        style: form
      - description: 検索期間の終了日時を指定します
        explode: true
        in: query
        name: ending_at
        required: false
        schema:
          format: date-time
          type: string
        style: form
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SpotReservation'
                type: array
          description: スポット予約 一覧を返します
      summary: スポット予約 一覧取得
      tags:
      - Spot Reservation API
    post:
      operationId: postSpotReservation
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpotReservationDetail'
          description: 予約の作成に成功しました。
      summary: スポット予約 新規作成
      tags:
      - Spot Reservation API
  /spot_reservations/{spot_reservation_id}:
    delete:
      operationId: deleteSpotReservation
      parameters:
      - explode: false
        in: path
        name: spot_reservation_id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        $ref: '#/components/requestBodies/inline_object_1'
      responses:
        '204':
          description: 指定されたスポット予約を削除します
      summary: スポット予約 削除 (複数スポットに紐づく予約データは削除不可)
      tags:
      - Spot Reservation API
    get:
      operationId: getSpotReservation
      parameters:
      - explode: false
        in: path
        name: spot_reservation_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SpotReservationDetail'
                type: array
          description: 指定されたスポット予約の詳細を返します
      summary: スポット予約 詳細取得
      tags:
      - Spot Reservation API
    patch:
      operationId: putSpotReservation
      parameters:
      - explode: false
        in: path
        name: spot_reservation_id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        $ref: '#/components/requestBodies/inline_object_2'
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SpotReservationDetail'
                type: array
          description: 指定されたスポット予約の更新結果を返します
      summary: スポット予約 更新
      tags:
      - Spot Reservation API
components:
  schemas:
    SpotReservation:
      example:
        spot_reservation_id: 00000000-0000-0000-0000-0000000000000
        spot_id: 00000000-0000-0000-0000-0000000000000
        starting_at: '2021-08-01T16:10:00+09:00'
        ending_at: '2021-08-01T17:10:00+09:00'
        invited_users:
        - user_id: 00000000-0000-0000-0000-0000000000000
        - user_id: 00000000-0000-0000-0000-0000000000000
        title: 〇〇の打ち合わせ
        description: 〇〇について話します
      properties:
        spot_reservation_id:
          type: string
        spot_id:
          type: string
        starting_at:
          format: date-time
          type: string
        ending_at:
          format: date-time
          type: string
        invited_users:
          items:
            $ref: '#/components/schemas/InvitedUser'
          type: array
        title:
          type: string
        description:
          type: string
    inline_object_1:
      example:
        send_mail: true
      properties:
        send_mail:
          type: boolean
      type: object
    SpotReservationDetail:
      example:
        spot_reservation_id: 00000000-0000-0000-0000-0000000000000
        spot_id: 00000000-0000-0000-0000-0000000000000
        starting_at: '2021-08-01T16:10:00+09:00'
        ending_at: '2021-08-01T17:10:00+09:00'
        invited_users:
        - user_id: 00000000-0000-0000-0000-0000000000000
        - user_id: 00000000-0000-0000-0000-0000000000000
        title: 〇〇の打ち合わせ
        description: 〇〇について話します
      properties:
        spot_reservation_id:
          type: string
        spot_id:
          type: string
        starting_at:
          format: date-time
          type: string
        ending_at:
          format: date-time
          type: string
        invited_users:
          items:
            $ref: '#/components/schemas/InvitedUser'
          type: array
        title:
          type: string
        description:
          type: string
    InvitedUser:
      example:
        user_id: 00000000-0000-0000-0000-0000000000000
      properties:
        user_id:
          type: string
    inline_object:
      example:
        spot_id: 00000000-0000-0000-0000-0000000000000
        starting_at: '2021-08-06T16:00:00+09:00'
        ending_at: '2021-08-06T17:00:00+09:00'
        send_mail: true
        invited_user_ids:
        - 00000000-0000-0000-0000-0000000000000
        - 00000000-0000-0000-0000-0000000000000
        title: 〇〇の打ち合わせ
        description: 〇〇について話します
      properties:
        spot_id:
          type: string
        starting_at:
          format: date-time
          type: string
        ending_at:
          format: date-time
          type: string
        send_mail:
          type: boolean
        invited_user_ids:
          items:
            type: string
          type: array
        title:
          type: string
        description:
          type: string
      type: object
    inline_object_2:
      example:
        starting_at: '2021-08-06T16:00:00+09:00'
        ending_at: '2021-08-06T17:00:00+09:00'
        send_mail: true
        invited_user_ids:
        - 00000000-0000-0000-0000-0000000000000
        - 00000000-0000-0000-0000-0000000000000
        title: 予約1
        description: 〇〇について話します
      properties:
        starting_at:
          format: date-time
          type: string
        ending_at:
          format: date-time
          type: string
        send_mail:
          type: boolean
        invited_user_ids:
          items:
            type: string
          type: array
        title:
          type: string
        description:
          type: string
      type: object
  requestBodies:
    inline_object_1:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object_1'
      required: true
    inline_object_2:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object_2'
      required: true
    inline_object:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object'
  securitySchemes:
    Bearer:
      description: Access token for API
      scheme: bearer
      type: http
